In [18]:
import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt

In [19]:
IMAGE_SIZE = 256
BATCH_SIZE = 32
CHANNELS = 3

In [20]:
dataset=tf.keras.preprocessing.image_dataset_from_directory(
    "../Plantvillage",
    shuffle=True,
    image_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE
)

Found 2152 files belonging to 3 classes.


In [21]:
class_names = dataset.class_names
class_names

['Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy']

In [22]:
len(dataset)

68

In [23]:
for image_batch, label_batch in dataset.take(1):
    print(image_batch.shape)
    print(label_batch.numpy())
    

(32, 256, 256, 3)
[0 1 0 0 0 1 0 0 1 2 1 2 1 0 1 0 0 0 0 1 2 1 0 1 1 1 2 0 0 0 0 1]


In [24]:
for image_batch, label_batch in dataset.take(1):
    print(image_batch[0])
    

tf.Tensor(
[[[193. 188. 185.]
  [194. 189. 186.]
  [193. 188. 185.]
  ...
  [199. 194. 198.]
  [198. 193. 197.]
  [192. 187. 191.]]

 [[189. 184. 181.]
  [191. 186. 183.]
  [191. 186. 183.]
  ...
  [195. 190. 194.]
  [197. 192. 196.]
  [194. 189. 193.]]

 [[184. 179. 176.]
  [188. 183. 180.]
  [190. 185. 182.]
  ...
  [195. 190. 194.]
  [198. 193. 197.]
  [197. 192. 196.]]

 ...

 [[134. 126. 124.]
  [147. 139. 137.]
  [151. 143. 141.]
  ...
  [149. 138. 146.]
  [140. 128. 138.]
  [145. 133. 143.]]

 [[139. 131. 129.]
  [147. 139. 137.]
  [151. 143. 141.]
  ...
  [157. 145. 157.]
  [148. 136. 150.]
  [148. 135. 152.]]

 [[138. 130. 128.]
  [137. 129. 127.]
  [141. 133. 131.]
  ...
  [149. 137. 151.]
  [145. 132. 150.]
  [152. 139. 157.]]], shape=(256, 256, 3), dtype=float32)


In [25]:
for image_batch, label_batch in dataset.take(1):
    print(image_batch[0].numpy())
    

[[[177. 181. 193.]
  [168. 172. 184.]
  [204. 208. 220.]
  ...
  [141. 145. 157.]
  [135. 139. 151.]
  [129. 133. 145.]]

 [[193. 197. 209.]
  [179. 183. 195.]
  [195. 199. 211.]
  ...
  [136. 140. 152.]
  [129. 133. 145.]
  [121. 125. 137.]]

 [[198. 202. 214.]
  [193. 197. 209.]
  [215. 219. 231.]
  ...
  [127. 131. 143.]
  [119. 123. 135.]
  [112. 116. 128.]]

 ...

 [[148. 146. 160.]
  [148. 146. 160.]
  [149. 147. 161.]
  ...
  [135. 133. 146.]
  [140. 138. 151.]
  [111. 109. 122.]]

 [[146. 144. 158.]
  [146. 144. 158.]
  [148. 146. 160.]
  ...
  [114. 112. 125.]
  [114. 112. 125.]
  [148. 146. 159.]]

 [[146. 144. 158.]
  [147. 145. 159.]
  [148. 146. 160.]
  ...
  [116. 114. 127.]
  [ 87.  85.  98.]
  [158. 156. 169.]]]
